stages:
 - build
 - test
 - deploy
test_container_crawler:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk upgrade
    - apk add --no-cache py-pip python 
    - apk add libffi-dev openssl-dev libgcc python-dev build-base
    - pip install --no-cache-dir docker-compose
#    - chmod +x /usr/local/bin/docker-compose
  script:
#    - cd test-environment/crawler
    - docker-compose up -d
    - docker-compose ps 
#    - docker login -u vdvas -p qweasd123
#    - docker pull vdvas/9a7c218a
#    - docker-compose exec crawler /bin/bash -c "python3 -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include crawler/crawler.py"
    - docker exec crawler_crawler_1 /bin/bash -c "python3 -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include crawler/crawler.py"

test_container_ui:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk upgrade
    - apk add --no-cache py-pip python
    - apk add libffi-dev openssl-dev libgcc python-dev build-base
    - pip install --no-cache-dir docker-compose
  script:
    - docker-compose up -d
    - docker-compose ps
    - docker exec crawler_ui_1 /bin/bash -c "python -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include ui/ui.py"
