stages:
 - build
 - test
 - deploy
build_job:
 stage: build
 script:
   - echo 'build'
test_unit_job:
 stage: test
 image: python:3.6
 script:
   - cd search_engine_crawler
   - pip install -r requirements.txt -r requirements-test.txt
   - python -m unittest discover -s tests/
   - coverage run -m unittest discover -s tests/
   - coverage report --include crawler.py
test_integration_job:
 stage: test
 script:
 - echo 'Testing 2'
deploy_job:
 stage: deploy
 script:
 - echo 'Deploy'
