stages:
 - build
 - test
 - deploy
#variables:
#  crawler_dir=search_engine_crawler
build:
  script:
    -docker build ./search_engine_crawler .
  artifacts:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA


test_crawler_job:
 stage: test
 image: python:3.6
 script:
   - cd search_engine_crawler
   - pip install -r requirements.txt -r requirements-test.txt
   - python -m unittest discover -s tests/
   - coverage run -m unittest discover -s tests/
   - coverage report --include crawler/crawler.py

test_ui_job:
 stage: test
 image: python:3.6
 script:
   - cd search_engine_ui
   - pip install -r requirements.txt -r requirements-test.txt
   - python -m unittest discover -s tests/ 
   - coverage run -m unittest discover -s tests/ 
   - coverage report --include ui/ui.py
