version: '3'
services:
  crawler:
    build: search_engine_crawler
    depends_on:
      - "mongodb"
      - "rabbitmq"
    tty: true
    restart: always
    networks:
      crawler:
        aliases:
          - crawler 
  ui:
    build: search_engine_ui
    depends_on:
      - "mongodb"
    tty: true
    ports:
      - "8000:8000"
    networks:
      crawler:
        aliases:
          - ui


  mongodb:
    image: "mongo:latest"
    networks:
      crawler:
        aliases:
          - mongo

  rabbitmq:
    build: rabbitmq
    ports:
      - "15672:15672"
    hostname: rabbitmq
    networks:
      crawler:
        aliases:
          - rabbitmq-test
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

networks:
  crawler:
